#!/usr/bin/env node

/**
 * Obscura Browser Detection Script
 * 
 * 用于 /harness test 阶段自动检测 Obscura 浏览器引擎是否可用
 * 并输出推荐配置
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

function checkObscura() {
  console.log('\n🌐 BROWSER CHECK - Obscura Detection\n');
  console.log('=' .repeat(50));

  try {
    const version = execSync('obscura --version 2>/dev/null', {
      encoding: 'utf-8',
      stdio: ['pipe', 'pipe', 'ignore'],
    }).trim();

    console.log(`✅ Obscura Detected: v${version}`);
    console.log('\n📋 Recommended Configuration:');
    console.log('- E2E Engine: Obscura (Primary)');
    console.log('- CDP Port: 9222');
    console.log('- Stealth Mode: Enabled');
    console.log('- Anti-Detection: Built-in');
    
    return {
      available: true,
      version,
      engine: 'obscura',
      config: {
        cdpPort: 9222,
        stealth: true,
        headless: true,
      },
    };
  } catch (error) {
    console.log('⚠️  Obscura Not Found');
    console.log('\n📦 Installation Instructions:');
    console.log('');
    console.log('# macOS Apple Silicon (M1/M2/M3/M4):');
    console.log('curl -LO https://github.com/h4ckf0r0day/obscura/releases/latest/download/obscura-aarch64-macos.tar.gz && \\');
    console.log('  tar xzf obscura-aarch64-macos.tar.gz && \\');
    console.log('  chmod +x obscura && sudo mv obscura /usr/local/bin/');
    console.log('');
    console.log('# Linux x86_64:');
    console.log('curl -LO https://github.com/h4ckf0r0day/obscura/releases/latest/download/obscura-x86_64-linux.tar.gz && \\');
    console.log('  tar xzf obscura-x86_64-linux.tar.gz && \\');
    console.log('  chmod +x obscura && sudo mv obscura /usr/local/bin/');
    console.log('');
    console.log('\n🔄 Fallback Configuration:');
    console.log('- E2E Engine: Headless Chrome (Fallback)');
    console.log('- Puppeteer/Playwright Compatible: Yes');
    console.log('- Performance Impact: ~7x slower than Obscura');
    
    return {
      available: false,
      version: null,
      engine: 'chrome',
      config: {
        headless: true,
        executablePath: null, // Use system Chrome
      },
    };
  } finally {
    console.log('\n' + '='.repeat(50));
  }
}

function generateViteConfig(obscuraResult) {
  const configContent = `
// Auto-generated by Obscura Detection Script
// Date: ${new Date().toISOString()}
// Engine: ${obscuraResult.engine} ${obscuraResult.version || '(Chrome Fallback)'}

import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import path from 'path';

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: './src/test-setup.ts',
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      exclude: ['node_modules/', 'src/test-setup.ts'],
    },
    ${obscuraResult.available ? `// Obscura E2E Config (v${obscuraResult.version})
    e2e: {
      browser: 'obscura',
      cdpPort: ${obscuraResult.config.cdpPort},
      stealth: true,
    },` : '// Using Headless Chrome for E2E (Obscura not installed)'},
  },
});
`;

  const configPath = path.join(process.cwd(), 'vite.config.ts');
  
  if (fs.existsSync(configPath)) {
    console.log(`\nℹ️  vite.config.ts already exists. Update manually if needed.`);
  } else {
    fs.writeFileSync(configPath, configContent.trim());
    console.log(`\n✅ Generated vite.config.ts with ${obscuraResult.engine} configuration`);
  }
}

if (require.main === module) {
  const result = checkObscura();
  
  if (process.argv.includes('--generate-config')) {
    generateViteConfig(result);
  }
  
  // Output JSON for programmatic use
  if (process.argv.includes('--json')) {
    console.log('\n---JSON_OUTPUT_START---');
    console.log(JSON.stringify(result, null, 2));
    console.log('---JSON_OUTPUT_END---');
  }
  
  process.exit(result.available ? 0 : 1);
}

module.exports = { checkObscura };
